### ISSUE TITLE
Consider using ASTCENC_FLG_SELF_DECOMPRESS_ONLY for compression

### ISSUE THREAD

**Issue by solidpixel** [alecazam/kram#10]
For your `astcenc` compressor contexts consider creating them with the `ASTCENC_FLG_SELF_DECOMPRESS_ONLY` flag. This allows the codec to repack the data tables with only the entries it needs for the compression configuration in use. However, it cannot reliably decompress arbitrary images as the table entries are missing for things the current compressor configuration isn't using, so only do this for compression-only contexts or cases where you are decompressing images made in the same compressor session. 

Using this option for compression give 10-20% more performance, depending on block size, so is highly recommended.

**Comment by solidpixel** [comment]
P.S. Not setting this flag seems to be the trigger for the image bug you've been hitting. Investigating that one now. The `astcenc` command line always sets it for compression contexts, which is why I've not been able to repro.

**EDIT:** Image bug should be fixed on astcenc `main`.

**Comment by alecazam** [comment]
Will look into that.  I also need to hookup the block diagnostics that you added a while back.

**Comment by alecazam** [comment]
I'm a little confused by the naming on this.  Is this for the compressor too?    I did add it just now.

I do use both the ASTC compress and decompress.  Decompress mostly on x64 where ASTC isn't supported, but I want to still display the pixels.   There's also this flag ASTCENC_FLG_DECOMPRESS_ONLY which I do set on the decompressor.

**Comment by solidpixel** [comment]
Yeah it's an odd name - couldn't think of a better one.

The flag is designed to help context creation and compression performance (optimize data tables for the specific config in use, rather than storing complete tables). 

Decompression is still supported, but only for the subset of block modes and partitionings that were needed by the compressor config, so it's only safe to use for decompressing images created in that compression session (i.e. for testing image quality by doing compress -> decompress pairs). For general arbitrary image compression, don't use it. 

Summary:

* Use `ASTCENC_FLG_SELF_DECOMPRESS_ONLY` on contexts you use for compression, or compression->decompression pairs. 
* Use `ASTCENC_FLG_DECOMPRESS_ONLY` on contexts you plan to use only for decompression.
* For arbitrary contexts which may compress and decompress arbitrary images then set neither.

**Comment by alecazam** [comment]
Closing this, and thanks for the suggestion.  I'll do some more timing numbers next week now that the bad blocks are fixed.
