### ISSUE TITLE
How to open DDS from this file?

### ISSUE THREAD

**Issue by VSO-plxe** [alecazam/kram#12]
I am green and have no idea how to extract it from this file: 940_2D_ST-16_LoadScreen_18fps.dds
[940_2D_ST-16_LoadScreen_18fps.zip](https://github.com/alecazam/kram/files/9157202/940_2D_ST-16_LoadScreen_18fps.zip)

**Comment by alecazam** [comment]
Looks like it's some DX9 DDS hack with a fourcc of "etc2".   There are 4 different ETC2 images with RGB/A/SRGB.   ETC2 is not even a DDS format.  Looks like whatever wrote it out didn't know how, and it doesn't really have enough to read it in.   

It's saying it's a 1948 width x1929 (really 1932) height x 2 depth image.   Even with a depth of 1, at 0.5Bpp it should have 1.8MB of image data.   But it only holds 1.3MB and crashes kramv trying to read it.

Sorry you're going to have to step through it the DDSHelper if you want to see it.   kram isn't really for image forensics, and is really meant for DX10 format images that were created by something valid.
