### ISSUE TITLE
KTX to TGA, PNG or DDS at least

### ISSUE THREAD

**Issue by GhostHeroine** [alecazam/kram#14]
Hello! I have a numerous of .ktx files, how i can convert them into tga or png or dds at least with kram?
[00001459.txt](https://github.com/alecazam/kram/files/11463034/00001459.txt)
[00001493.txt](https://github.com/alecazam/kram/files/11463036/00001493.txt)

They are actually .ktx, but for uploding to GitHub i had to rename them into .txt

**Comment by alecazam** [comment]
Sure kram supports reading ktx/png/ktx2/dds and outputting dds/png.  I'm not going to deal with tga.  See the scripts directory, or run kram for cli help.
