### ISSUE TITLE
Provide binary builds?

### ISSUE THREAD

**Issue by thecbloom** [alecazam/kram#2]
Kram looks interesting.  It would be great if you'd provide binary releases!

**Comment by alecazam** [comment]
Working on CI.  No dmg yet either, but it will build the bin directories, so the CLI, libs, and kramv app.

**Comment by alecazam** [comment]
Okay, I first used TravisCI and then ran out of credits, so the builds are now using Github Actions.  Had to work through 4 days trying to setup very basic CI with examples and actions that just don't work, but it's finally creating macOS and Windows builds.  No DMG on the Mac, and no framework.  Just static libs and the cli and viewer app.  So headers are still in the main source.
